---
aaddons:
  script:
    - sonar-scanner
  sonarcloud:
    organization: luispemorarod
    token:
      secure: O7kJ77H6gF/6GQPXaOCy2WydmFOXZpiBOKw1EDuYfSj15sGDervzZJRK0D/ZAtQ8EHIgLK3l5YvyCqL/PDVU1dXlwMVIe+XRuhhDbkga0fJAYO/mN43hkIgLTDRmUvb10WSJY1CjcfkfGK0cNKuJ2QezaCxl5be3juv6U64Dz/18RQ6QsEYhnwkpMumN7xeEAEClVLhgRfP3poSeN4D5dBOXzL6pEFss2HYsqTd3vAXEuyxdxMFfs5a7cArKw+XRSi0Ck5M/zI2dbdWJSP13So+Fi9XeL2wamlUhubflr+LpGPyUakL570BVnVDOvEglYf/kOnP6z5PR/aBWSisPyiTUHwn9VvrVP8y1SZvZk4PjO3SPdJ7eEutOABGM3HkSYGucB7Y3/PRL9e2WrkMDo7YG1Vbl3zoy9FQibdS/gM0HSe4/+CFRJ9oK4eujhukoCq/dSHgn+sMBI8nQTWGJ+FVfW7Ab1rd4bKdii0UZb1rHVyvzyMgm/xwurmquMev3vawmwx/A7q0nHsw9Oy7/MkQ3RLwSIk6HxqVYWFPauEEQ5Jn1MtJQMZEqc0VPdy5Gj29A6WVF/8oe6zMitjoIKgWBOiRbAInRr15VUP1BLAsdYXQMd8po+cXxDzc8zBtDyQWKf2m3R/ewOlf6VjB2liZnd04H+Jw+M2l50xXMQb4=
deploy:
  api_key:
    secure: f/ukTtRD096iIhuM4GQHUifSJPe+YvJlsimQI2TQfQzSbtCMiwyf2PiWETwXlKXje1+FBRDv6E7lxfRWGamN9PnB5MnzOIJyHpZnfu7vGF4s/+vTx4siZ269adH1oneYuDcPKXGivdhnxqoyLRPzyPgtW1tqJTZjrho//6lk8C2NTpUsppoiKz3sCBGpHz6ZRRX0LJ1f4uHIXccFkWUrRXA2c5U2eHYtTC2DAl6EyJKtcu2uzrp9tMGxfiBnN2xmYy6ramnpJTsFB4PQ7vPfJQfIDQ5gU+uJ8TI0BqGIE8Vfq/LXeNdpaYxLO9bUHJ18AqGpQ+A8dqPAACvW+0ZAObPX0KxbX4glt4v7H70HmMN5tCkj2FsuG2hG0rVxM41SxSSfReUfgBHTPdq2JSKW3IRSMY6eHXmOxTfJeLdN3fuiwZykp3N/bLfV4u17NjDNjvN4Md0jGRCbQIpao77Jys+Bkukubkn7FyfX5XikpslKMNWYOKp0oZDMOYr6j9j/7bsTr34rDl1SVUorlJr9qK/0RHdgqmDDXR50YllzPyv471WOjyR9FYhKpco6wQrNWjlmR/yNWm80dlMdnzuMMsQR2BLA84ykqISktxVx/pNfB12jnX8U+vXdlhl08q5BfTrabpsC40B4sVSoThrLxLCStmKExepzmoAlhTc6em8=
  app: golang-pokemon-api
  provider: heroku
env: GO111MODULE=on
language: go

